/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/workers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get worker by ID */
        get: operations["findById"];
        /** Update worker */
        put: operations["update"];
        post?: never;
        /**
         * Delete worker
         * @description Soft-deletes the worker
         */
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get user by ID */
        get: operations["findById_1"];
        /**
         * Update user
         * @description Email, name, role, language, assigned properties, and status
         */
        put: operations["update_1"];
        post?: never;
        /**
         * Deactivate user
         * @description Sets status to INACTIVE. Never a hard delete: users are referenced by history (e.g. confirmed stays).
         */
        delete: operations["deactivate"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stays/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get stay by ID */
        get: operations["findById_2"];
        /**
         * Update stay
         * @description Change dates or room. Runs constraint engine.
         */
        put: operations["update_2"];
        post?: never;
        /** Cancel stay */
        delete: operations["cancel"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/properties/{propertyId}/rooms/{roomId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get room by ID */
        get: operations["findById_3"];
        /** Update room */
        put: operations["update_3"];
        post?: never;
        /**
         * Delete room
         * @description Permanently deletes the room. Refused while any stay still references it.
         */
        delete: operations["delete_1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/properties/{propertyId}/rooms/{roomId}/beds/{bedId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get bed by ID */
        get: operations["findById_4"];
        /** Update bed (rename or change status) */
        put: operations["update_4"];
        post?: never;
        /**
         * Delete bed
         * @description Permanently deletes the bed.
         */
        delete: operations["delete_2"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/properties/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get property by ID */
        get: operations["findById_5"];
        /** Update property */
        put: operations["update_5"];
        post?: never;
        /**
         * Delete property
         * @description Permanently deletes the property. Refused while any room or stay still references it.
         */
        delete: operations["delete_3"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List workers
         * @description Paginated list with optional filters: status, gender, tag, name search
         */
        get: operations["findAll"];
        put?: never;
        /** Create worker */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workers/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import workers from CSV
         * @description Parse and create workers from a CSV file. Returns per-row summary: created/skipped/errors
         */
        post: operations["importCsv"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List users
         * @description Paginated list with optional filters: role, status, name/email search
         */
        get: operations["findAll_1"];
        put?: never;
        /** Create user */
        post: operations["create_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stays": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List stays
         * @description Paginated list filterable by worker, property, status, and date range
         */
        get: operations["findAll_2"];
        put?: never;
        /**
         * Plan a stay
         * @description Creates a planned stay. Runs constraint engine — returns 422 with violations if hard constraints are breached.
         */
        post: operations["create_2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stays/{id}/no-show": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * No-show
         * @description Mark a stay as no_show with a reason tag
         */
        post: operations["noShow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stays/{id}/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Move worker to another room
         * @description Atomic operation: checks out from current room, creates new stay in target room
         */
        post: operations["move"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stays/{id}/check-out": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Check out
         * @description Transitions a checked_in stay to checked_out. Sets actual departure date if different from planned.
         */
        post: operations["checkOut"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stays/{id}/check-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Check in
         * @description Transitions an expected_today stay to checked_in. Runs constraint engine. Optionally overrides room.
         */
        post: operations["checkIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stays/bulk-checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bulk checkout stays
         * @description Checks out multiple checked_in stays in one call. Returns per-item results.
         */
        post: operations["bulkCheckout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stays/bulk-assign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bulk assign stays
         * @description Creates multiple planned stays in one call. Returns per-item results including constraint violations.
         */
        post: operations["bulkAssign"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/properties": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List properties
         * @description Paginated list with optional status and name filters
         */
        get: operations["findAll_3"];
        put?: never;
        /** Create property */
        post: operations["create_3"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/properties/{propertyId}/rooms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List rooms in a property */
        get: operations["findAll_4"];
        put?: never;
        /** Create room */
        post: operations["create_4"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/properties/{propertyId}/rooms/{roomId}/beds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List beds in a room */
        get: operations["findAll_5"];
        put?: never;
        /** Create a single bed */
        post: operations["create_5"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/properties/{propertyId}/rooms/{roomId}/beds/bulk-generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bulk-generate beds
         * @description Adds count sequentially numbered beds after the room's current highest numeric label
         */
        post: operations["bulkGenerate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/properties/{propertyId}/inspection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Inspection roster
         * @description Room-by-room roster for nightly inspection
         */
        get: operations["getInspectionRoster"];
        put?: never;
        /**
         * Submit inspection report
         * @description Reports discrepancies: expected workers not present, unexpected workers present
         */
        post: operations["submitInspectionReport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh token
         * @description Exchange a valid refresh token for a new token pair
         */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Authenticate with email and password, receive access + refresh tokens
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stays/arrivals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Arrivals list
         * @description Returns expected_today stays for a property on a given date
         */
        get: operations["getArrivals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/properties/{propertyId}/occupancy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Room occupancy
         * @description Returns room-by-room list of current occupants for a property on a given date
         */
        get: operations["getOccupancy"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/properties/{propertyId}/occupancy/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export occupancy CSV
         * @description Downloads nightly occupancy list as CSV. Supports language parameter (EN, PL, DE, RU, UA).
         */
        get: operations["exportOccupancy"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/properties/{propertyId}/exceptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Occupancy exceptions
         * @description Returns over-capacity rooms and unassigned stays for a property on a given date
         */
        get: operations["getExceptions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/properties/{propertyId}/exceptions/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export exceptions CSV
         * @description Downloads exception report as CSV. Supports language parameter (EN, PL, DE, RU, UA).
         */
        get: operations["exportExceptions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/properties/{propertyId}/arrivals/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export arrivals CSV
         * @description Downloads arrivals list as CSV. Supports language parameter (EN, PL, DE, RU, UA).
         */
        get: operations["exportArrivals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current user
         * @description Return the authenticated user's profile
         */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Query audit events
         * @description Paginated audit trail filterable by entity type, entity ID, actor user, and date range
         */
        get: operations["findAll_6"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UpdateWorkerRequest: {
            firstName: string;
            lastName: string;
            /** @enum {string} */
            gender: "MALE" | "FEMALE" | "OTHER";
            nationality?: string;
            phone?: string;
            email?: string;
            /** Format: date */
            dateOfBirth?: string;
            tags?: string[];
            notes?: string;
            /** @enum {string} */
            status: "ACTIVE" | "INACTIVE" | "DELETED";
        };
        WorkerResponse: {
            /** Format: uuid */
            id?: string;
            internalId?: string;
            firstName?: string;
            lastName?: string;
            /** @enum {string} */
            gender?: "MALE" | "FEMALE" | "OTHER";
            nationality?: string;
            phone?: string;
            email?: string;
            /** Format: date */
            dateOfBirth?: string;
            tags?: string[];
            notes?: string;
            /** @enum {string} */
            status?: "ACTIVE" | "INACTIVE" | "DELETED";
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        UpdateUserRequest: {
            email: string;
            firstName: string;
            lastName: string;
            /** @enum {string} */
            role: "AGENCY_ADMIN" | "AGENCY_PLANNER" | "PROPERTY_ADMIN" | "FRONT_DESK";
            language?: string;
            assignedPropertyIds?: string[];
            /** @enum {string} */
            status: "ACTIVE" | "INACTIVE";
        };
        UserResponse: {
            /** Format: uuid */
            id?: string;
            email?: string;
            firstName?: string;
            lastName?: string;
            /** @enum {string} */
            role?: "AGENCY_ADMIN" | "AGENCY_PLANNER" | "PROPERTY_ADMIN" | "FRONT_DESK";
            language?: string;
            assignedPropertyIds?: string[];
            /** @enum {string} */
            status?: "ACTIVE" | "INACTIVE";
            /** Format: date-time */
            lastLoginAt?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        UpdateStayRequest: {
            /** Format: uuid */
            roomId: string;
            /** Format: uuid */
            bedId?: string;
            /** Format: date */
            dateFrom: string;
            /** Format: date */
            dateTo?: string;
            overrideReason?: string;
            notes?: string;
        };
        StayResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            workerId?: string;
            /** Format: uuid */
            propertyId?: string;
            /** Format: uuid */
            roomId?: string;
            /** Format: uuid */
            bedId?: string;
            bedAutoAssigned?: boolean;
            /** Format: date */
            dateFrom?: string;
            /** Format: date */
            dateTo?: string;
            /** @enum {string} */
            status?: "PLANNED" | "EXPECTED_TODAY" | "CHECKED_IN" | "CHECKED_OUT" | "CANCELLED" | "NO_SHOW";
            overrideReason?: string;
            noShowReason?: string;
            notes?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        UpdateRoomRequest: {
            roomNumber: string;
            /** Format: int32 */
            floor?: number;
            /** @enum {string} */
            genderRule: "MIXED" | "MALE_ONLY" | "FEMALE_ONLY";
            /** @enum {string} */
            status: "ACTIVE" | "BLOCKED";
            notes?: string;
        };
        OccupantWorker: {
            /** Format: uuid */
            id?: string;
            internalId?: string;
            firstName?: string;
            lastName?: string;
            /** @enum {string} */
            gender?: "MALE" | "FEMALE" | "OTHER";
        };
        RoomOccupant: {
            /** Format: uuid */
            stayId?: string;
            worker?: components["schemas"]["OccupantWorker"];
            /** Format: date */
            dateFrom?: string;
            /** Format: date */
            dateTo?: string;
            /** @enum {string} */
            status?: "PLANNED" | "EXPECTED_TODAY" | "CHECKED_IN" | "CHECKED_OUT" | "CANCELLED" | "NO_SHOW";
        };
        RoomResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            propertyId?: string;
            roomNumber?: string;
            /** Format: int32 */
            floor?: number;
            /** Format: int32 */
            bedCount?: number;
            /** Format: int32 */
            availableBedCount?: number;
            /** @enum {string} */
            genderRule?: "MIXED" | "MALE_ONLY" | "FEMALE_ONLY";
            /** @enum {string} */
            status?: "ACTIVE" | "BLOCKED";
            notes?: string;
            /** Format: int32 */
            currentOccupancy?: number;
            occupants?: components["schemas"]["RoomOccupant"][];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        UpdateBedRequest: {
            label: string;
            /** @enum {string} */
            status: "ACTIVE" | "BLOCKED";
        };
        BedResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            roomId?: string;
            label?: string;
            /** @enum {string} */
            status?: "ACTIVE" | "BLOCKED";
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        UpdatePropertyRequest: {
            name: string;
            address?: string;
            city?: string;
            notes?: string;
            /** @enum {string} */
            status: "ACTIVE" | "INACTIVE";
        };
        PropertyResponse: {
            /** Format: uuid */
            id?: string;
            name?: string;
            address?: string;
            city?: string;
            /** @enum {string} */
            status?: "ACTIVE" | "INACTIVE";
            notes?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        CreateWorkerRequest: {
            internalId: string;
            firstName: string;
            lastName: string;
            /** @enum {string} */
            gender: "MALE" | "FEMALE" | "OTHER";
            nationality?: string;
            phone?: string;
            email?: string;
            /** Format: date */
            dateOfBirth?: string;
            tags?: string[];
            notes?: string;
        };
        WorkerImportError: {
            /** Format: int32 */
            row?: number;
            internalId?: string;
            reason?: string;
        };
        WorkerImportResult: {
            /** Format: int32 */
            created?: number;
            /** Format: int32 */
            skipped?: number;
            /** Format: int32 */
            errors?: number;
            errorDetails?: components["schemas"]["WorkerImportError"][];
        };
        CreateUserRequest: {
            email: string;
            password: string;
            firstName: string;
            lastName: string;
            /** @enum {string} */
            role: "AGENCY_ADMIN" | "AGENCY_PLANNER" | "PROPERTY_ADMIN" | "FRONT_DESK";
            language?: string;
            assignedPropertyIds?: string[];
        };
        CreateStayRequest: {
            /** Format: uuid */
            workerId: string;
            /** Format: uuid */
            propertyId: string;
            /** Format: uuid */
            roomId: string;
            /** Format: uuid */
            bedId?: string;
            /** Format: date */
            dateFrom: string;
            /** Format: date */
            dateTo?: string;
            overrideReason?: string;
            notes?: string;
        };
        NoShowRequest: {
            noShowReason: string;
        };
        MoveRequest: {
            /** Format: uuid */
            targetRoomId: string;
            /** Format: uuid */
            targetBedId?: string;
            overrideReason?: string;
        };
        CheckOutRequest: {
            /** Format: date */
            actualDateTo?: string;
        };
        CheckInRequest: {
            /** Format: uuid */
            roomId?: string;
            /** Format: uuid */
            bedId?: string;
            overrideReason?: string;
        };
        BulkCheckoutRequest: {
            stayIds: string[];
        };
        BulkCheckoutResult: {
            /** Format: int32 */
            checkedOut?: number;
            /** Format: int32 */
            errors?: number;
            results?: components["schemas"]["CheckoutResult"][];
        };
        CheckoutResult: {
            /** Format: uuid */
            stayId?: string;
            status?: string;
            errorCode?: string;
        };
        Assignment: {
            /** Format: uuid */
            workerId: string;
            /** Format: uuid */
            propertyId: string;
            /** Format: uuid */
            roomId: string;
            /** Format: uuid */
            bedId?: string;
            /** Format: date */
            dateFrom: string;
            /** Format: date */
            dateTo?: string;
            overrideReason?: string;
        };
        BulkAssignRequest: {
            assignments: components["schemas"]["Assignment"][];
        };
        AssignmentResult: {
            /** Format: int32 */
            index?: number;
            /** Format: uuid */
            workerId?: string;
            /** Format: uuid */
            stayId?: string;
            /** Format: uuid */
            bedId?: string;
            status?: string;
            errorCode?: string;
        };
        BulkAssignResult: {
            /** Format: int32 */
            created?: number;
            /** Format: int32 */
            errors?: number;
            results?: components["schemas"]["AssignmentResult"][];
        };
        CreatePropertyRequest: {
            name: string;
            address?: string;
            city?: string;
            notes?: string;
        };
        CreateRoomRequest: {
            roomNumber: string;
            /** Format: int32 */
            floor?: number;
            /** @enum {string} */
            genderRule?: "MIXED" | "MALE_ONLY" | "FEMALE_ONLY";
            notes?: string;
        };
        CreateBedRequest: {
            label: string;
        };
        BulkGenerateBedsRequest: {
            /** Format: int32 */
            count?: number;
        };
        InspectionReportRequest: {
            rooms: components["schemas"]["RoomActualOccupancy"][];
        };
        RoomActualOccupancy: {
            /** Format: uuid */
            roomId: string;
            presentWorkerIds: string[];
        };
        InspectionDiscrepancyResponse: {
            discrepancies?: components["schemas"]["RoomDiscrepancy"][];
            hasDiscrepancies?: boolean;
        };
        RoomDiscrepancy: {
            /** Format: uuid */
            roomId?: string;
            roomNumber?: string;
            items?: components["schemas"]["WorkerDiscrepancy"][];
        };
        WorkerDiscrepancy: {
            /** Format: uuid */
            workerId?: string;
            discrepancyType?: string;
        };
        RefreshRequest: {
            refreshToken: string;
        };
        AuthResponse: {
            accessToken?: string;
            refreshToken?: string;
            /** Format: int64 */
            expiresIn?: number;
            user?: components["schemas"]["UserInfo"];
        };
        UserInfo: {
            id?: string;
            email?: string;
            firstName?: string;
            lastName?: string;
            role?: string;
            language?: string;
            assignedPropertyIds?: string[];
        };
        LoginRequest: {
            email: string;
            password: string;
        };
        Pageable: {
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            sort?: string[];
        };
        PageResponseWorkerResponse: {
            content?: components["schemas"]["WorkerResponse"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
        };
        PageResponseUserResponse: {
            content?: components["schemas"]["UserResponse"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
        };
        PageResponseStayResponse: {
            content?: components["schemas"]["StayResponse"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
        };
        PageResponsePropertyResponse: {
            content?: components["schemas"]["PropertyResponse"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
        };
        PageResponseRoomResponse: {
            content?: components["schemas"]["RoomResponse"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
        };
        OccupantSummary: {
            /** Format: uuid */
            stayId?: string;
            /** Format: uuid */
            workerId?: string;
            firstName?: string;
            lastName?: string;
            /** Format: uuid */
            bedId?: string;
            bedLabel?: string;
        };
        RoomOccupancyResponse: {
            /** Format: uuid */
            roomId?: string;
            roomNumber?: string;
            /** Format: int32 */
            floor?: number;
            /** Format: int32 */
            bedCount?: number;
            /** Format: int32 */
            availableBedCount?: number;
            /** Format: int32 */
            occupiedSpots?: number;
            occupants?: components["schemas"]["OccupantSummary"][];
        };
        InspectionRoomEntry: {
            /** Format: uuid */
            roomId?: string;
            roomNumber?: string;
            /** Format: int32 */
            floor?: number;
            expectedOccupants?: components["schemas"]["OccupantSummary"][];
            checkedInOccupants?: components["schemas"]["OccupantSummary"][];
        };
        OccupancyExceptionResponse: {
            /** Format: uuid */
            roomId?: string;
            roomNumber?: string;
            exceptionType?: string;
            /** Format: int32 */
            bedCount?: number;
            /** Format: int32 */
            availableBedCount?: number;
            /** Format: int32 */
            occupiedSpots?: number;
            occupants?: components["schemas"]["OccupantSummary"][];
        };
        AuditEventResponse: {
            /** Format: uuid */
            id?: string;
            /** @enum {string} */
            entityType?: "STAY" | "WORKER" | "ROOM" | "PROPERTY" | "BED" | "USER";
            /** Format: uuid */
            entityId?: string;
            /** @enum {string} */
            action?: "CREATED" | "UPDATED" | "DELETED" | "CHECKED_IN" | "CHECKED_OUT" | "NO_SHOW" | "CANCELLED" | "MOVED" | "BULK_ASSIGNED" | "BULK_CHECKED_OUT";
            /** Format: uuid */
            actorUserId?: string;
            previousState?: {
                [key: string]: Record<string, never>;
            };
            newState?: {
                [key: string]: Record<string, never>;
            };
            reason?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        PageResponseAuditEventResponse: {
            content?: components["schemas"]["AuditEventResponse"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    findById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WorkerResponse"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateWorkerRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WorkerResponse"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Worker deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    findById_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    update_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserRequest"];
            };
        };
        responses: {
            /** @description Email already in use, or this is the agency's last active admin */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    deactivate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User deactivated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Cannot deactivate yourself, or the agency's last active admin */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    findById_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StayResponse"];
                };
            };
        };
    };
    update_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateStayRequest"];
            };
        };
        responses: {
            /** @description Constraint violation */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StayResponse"];
                };
            };
        };
    };
    cancel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stay cancelled */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    findById_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                propertyId: string;
                roomId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RoomResponse"];
                };
            };
        };
    };
    update_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                propertyId: string;
                roomId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRoomRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RoomResponse"];
                };
            };
        };
    };
    delete_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                propertyId: string;
                roomId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Room deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Room still has referencing stays */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    findById_4: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                propertyId: string;
                roomId: string;
                bedId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BedResponse"];
                };
            };
        };
    };
    update_4: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                propertyId: string;
                roomId: string;
                bedId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateBedRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BedResponse"];
                };
            };
        };
    };
    delete_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                propertyId: string;
                roomId: string;
                bedId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bed deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    findById_5: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PropertyResponse"];
                };
            };
        };
    };
    update_5: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePropertyRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PropertyResponse"];
                };
            };
        };
    };
    delete_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Property deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Property still has rooms or referencing stays */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    findAll: {
        parameters: {
            query: {
                status?: "ACTIVE" | "INACTIVE" | "DELETED";
                gender?: "MALE" | "FEMALE" | "OTHER";
                tag?: string;
                search?: string;
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseWorkerResponse"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWorkerRequest"];
            };
        };
        responses: {
            /** @description Worker created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WorkerResponse"];
                };
            };
        };
    };
    importCsv: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WorkerImportResult"];
                };
            };
        };
    };
    findAll_1: {
        parameters: {
            query: {
                role?: "AGENCY_ADMIN" | "AGENCY_PLANNER" | "PROPERTY_ADMIN" | "FRONT_DESK";
                status?: "ACTIVE" | "INACTIVE";
                search?: string;
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseUserResponse"];
                };
            };
        };
    };
    create_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description User created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
            /** @description Email already in use */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    findAll_2: {
        parameters: {
            query: {
                workerId?: string;
                propertyId?: string;
                status?: "PLANNED" | "EXPECTED_TODAY" | "CHECKED_IN" | "CHECKED_OUT" | "CANCELLED" | "NO_SHOW";
                dateFrom?: string;
                dateTo?: string;
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseStayResponse"];
                };
            };
        };
    };
    create_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateStayRequest"];
            };
        };
        responses: {
            /** @description Stay planned */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StayResponse"];
                };
            };
            /** @description Constraint violation */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StayResponse"];
                };
            };
        };
    };
    noShow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoShowRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StayResponse"];
                };
            };
        };
    };
    move: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveRequest"];
            };
        };
        responses: {
            /** @description Constraint violation on target room */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StayResponse"];
                };
            };
        };
    };
    checkOut: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckOutRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StayResponse"];
                };
            };
        };
    };
    checkIn: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckInRequest"];
            };
        };
        responses: {
            /** @description Constraint violation — re-submit with overrideReason to force */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StayResponse"];
                };
            };
        };
    };
    bulkCheckout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkCheckoutRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BulkCheckoutResult"];
                };
            };
        };
    };
    bulkAssign: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkAssignRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BulkAssignResult"];
                };
            };
        };
    };
    findAll_3: {
        parameters: {
            query: {
                status?: "ACTIVE" | "INACTIVE";
                search?: string;
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponsePropertyResponse"];
                };
            };
        };
    };
    create_3: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePropertyRequest"];
            };
        };
        responses: {
            /** @description Property created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PropertyResponse"];
                };
            };
        };
    };
    findAll_4: {
        parameters: {
            query: {
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path: {
                propertyId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseRoomResponse"];
                };
            };
        };
    };
    create_4: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                propertyId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRoomRequest"];
            };
        };
        responses: {
            /** @description Room created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RoomResponse"];
                };
            };
        };
    };
    findAll_5: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                propertyId: string;
                roomId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BedResponse"][];
                };
            };
        };
    };
    create_5: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                propertyId: string;
                roomId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBedRequest"];
            };
        };
        responses: {
            /** @description Bed created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BedResponse"];
                };
            };
        };
    };
    bulkGenerate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                propertyId: string;
                roomId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkGenerateBedsRequest"];
            };
        };
        responses: {
            /** @description Beds created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BedResponse"][];
                };
            };
        };
    };
    getInspectionRoster: {
        parameters: {
            query?: {
                date?: string;
            };
            header?: never;
            path: {
                propertyId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["InspectionRoomEntry"][];
                };
            };
        };
    };
    submitInspectionReport: {
        parameters: {
            query?: {
                date?: string;
            };
            header?: never;
            path: {
                propertyId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InspectionReportRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["InspectionDiscrepancyResponse"];
                };
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Tokens refreshed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Invalid or expired refresh token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Tokens issued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
    getArrivals: {
        parameters: {
            query: {
                propertyId: string;
                date?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StayResponse"][];
                };
            };
        };
    };
    getOccupancy: {
        parameters: {
            query?: {
                date?: string;
            };
            header?: never;
            path: {
                propertyId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RoomOccupancyResponse"][];
                };
            };
        };
    };
    exportOccupancy: {
        parameters: {
            query?: {
                date?: string;
                language?: string;
            };
            header?: never;
            path: {
                propertyId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    getExceptions: {
        parameters: {
            query?: {
                date?: string;
            };
            header?: never;
            path: {
                propertyId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OccupancyExceptionResponse"][];
                };
            };
        };
    };
    exportExceptions: {
        parameters: {
            query?: {
                date?: string;
                language?: string;
            };
            header?: never;
            path: {
                propertyId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    exportArrivals: {
        parameters: {
            query?: {
                date?: string;
                language?: string;
            };
            header?: never;
            path: {
                propertyId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User info returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserInfo"];
                };
            };
        };
    };
    findAll_6: {
        parameters: {
            query: {
                entityType?: "STAY" | "WORKER" | "ROOM" | "PROPERTY" | "BED" | "USER";
                entityId?: string;
                actorUserId?: string;
                dateFrom?: string;
                dateTo?: string;
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseAuditEventResponse"];
                };
            };
        };
    };
}
